// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServicerClient is the client API for Servicer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServicerClient interface {
	TestIt(ctx context.Context, in *Inp, opts ...grpc.CallOption) (*Inp, error)
}

type servicerClient struct {
	cc grpc.ClientConnInterface
}

func NewServicerClient(cc grpc.ClientConnInterface) ServicerClient {
	return &servicerClient{cc}
}

func (c *servicerClient) TestIt(ctx context.Context, in *Inp, opts ...grpc.CallOption) (*Inp, error) {
	out := new(Inp)
	err := c.cc.Invoke(ctx, "/api.Servicer/TestIt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServicerServer is the server API for Servicer service.
// All implementations must embed UnimplementedServicerServer
// for forward compatibility
type ServicerServer interface {
	TestIt(context.Context, *Inp) (*Inp, error)
	mustEmbedUnimplementedServicerServer()
}

// UnimplementedServicerServer must be embedded to have forward compatible implementations.
type UnimplementedServicerServer struct {
}

func (UnimplementedServicerServer) TestIt(context.Context, *Inp) (*Inp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestIt not implemented")
}
func (UnimplementedServicerServer) mustEmbedUnimplementedServicerServer() {}

// UnsafeServicerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServicerServer will
// result in compilation errors.
type UnsafeServicerServer interface {
	mustEmbedUnimplementedServicerServer()
}

func RegisterServicerServer(s grpc.ServiceRegistrar, srv ServicerServer) {
	s.RegisterService(&Servicer_ServiceDesc, srv)
}

func _Servicer_TestIt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Inp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicerServer).TestIt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Servicer/TestIt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicerServer).TestIt(ctx, req.(*Inp))
	}
	return interceptor(ctx, in, info, handler)
}

// Servicer_ServiceDesc is the grpc.ServiceDesc for Servicer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Servicer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Servicer",
	HandlerType: (*ServicerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestIt",
			Handler:    _Servicer_TestIt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bin/api/api.proto",
}
